version: '3'
services:
  frontend:
    build: frontend/ 
  backend:
    build: backend/
  database:
    image: betrybe/docker-compose-example-database:v1

# build especifica o path onde tem um Dockerfile a ser bildado
# image especifica uma imagem local ou a ser baixada